version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    network_mode: host
    volumes:
      - hasura_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: bsv
      POSTGRES_DB: bsv
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    network_mode: host
    #ports:
    #  - "127.0.0.1:8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://bsv:postgrespassword@127.0.0.1:5432/bsv
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  repro:
    build: .
    network_mode: host
    depends_on:
        - "graphql-engine"

volumes:
  hasura_data:

